---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\GraphQLClientBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    IDCI\Bundle\GraphQLClientBundle\Client\GraphQLApiClient:
        abstract: true
        arguments: ['@logger', null, null, null]

    IDCI\Bundle\GraphQLClientBundle\Client\GraphQLApiClientRegistry: ~
