---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\GraphQLClientBundle\:
        resource: '../src/*'
        exclude: '../src/{Entity,Repository,Tests}'

    # Client
    IDCI\Bundle\GraphQLClientBundle\Client\GraphQLApiClient:
        abstract: true

    IDCI\Bundle\GraphQLClientBundle\Client\GraphQLApiClientRegistry: ~
